name: Rozak Buhari
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: none
gems:
  - jekyll-feed
url:  https://rozakbuhari.github.io
# url:  http://localhost:3000
