name: Rozak Buhari
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
permalink: none
gems:
  - jekyll-feed
url:  http://localhost:3000
